# **Importações**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import string
import re
import pickle

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegression

import pickle

# **Pre processamento de texto**

In [4]:
def wordopt(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]','',text)
    text = re.sub(r"\\W"," ",text)
    text = re.sub(r'https?://\S+|www\.\S+','',text)
    text = re.sub(r'<.*?>+',b'',text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation),'',text)
    text = re.sub(r'\w*\d\w*','',text)
    return text

In [5]:
text = """
Kátia Abreu diz que vai colocar sua expulsão em uma moldura, mas não para de reclamar.	
A senadora Kátia Abreu (sem partido-TO) disse que sua expulsão do PMDB foi resultado de uma ação da cúpula atual da legenda que, segundo ela, é oportunista.
“Amanhã eu vou botar numa moldura dourada a minha expulsão, porque das mãos de onde veio, é um atestado de boa conduta para o meu currículo. Essas pessoas que me expulsaram não servem ao país. Eles se servem do país em seus benefícios próprios”, disse Kátia Abreu.
Ué, mas se a expulsão é algo tão bom para seu currículo, por que tanta choradeira, Kátia?
Sabemos o motivo. Provavelmente Kátia não tem valor para o PT, partido que já deveria tê-la absorvido. Ao que parece o PT gostava de Kátia somente se ela ficasse entrincheirada dentro do PMDB.
Ou seja, isso é se rebaixar demais. Resta a Kátia ficar chorando as pitangas por todos os cantos.
Em tempo: até o momento o PT não cadastrou Kátia Abreu em suas fileiras. Que situação patética para a ex-ministra da Agricultura de Dilma.
"""

In [7]:
print(wordopt(text))

kátia abreu diz que vai colocar sua expulsão em uma moldura mas não para de reclamar
a senadora kátia abreu sem partidoto disse que sua expulsão do pmdb foi resultado de uma ação da cúpula atual da legenda que segundo ela é oportunista
“amanhã eu vou botar numa moldura dourada a minha expulsão porque das mãos de onde veio é um atestado de boa conduta para o meu currículo essas pessoas que me expulsaram não servem ao país eles se servem do país em seus benefícios próprios” disse kátia abreu
ué mas se a expulsão é algo tão bom para seu currículo por que tanta choradeira kátia
sabemos o motivo provavelmente kátia não tem valor para o pt partido que já deveria têla absorvido ao que parece o pt gostava de kátia somente se ela ficasse entrincheirada dentro do pmdb
ou seja isso é se rebaixar demais resta a kátia ficar chorando as pitangas por todos os cantos
em tempo até o momento o pt não cadastrou kátia abreu em suas fileiras que situação patética para a exministra da agricultura de dilma

# **Leitura dos dados**

In [15]:
news = pd.read_csv(r'preprocessed\pre-processed.csv')
news.drop(axis='columns', columns=['index'], inplace=True)
news.head()

  label                                  preprocessed_news
0  fake  katia abreu diz vai colocar expulsao moldura n...
1  fake  ray peita bolsonaro conservador fake entrevist...
2  fake  reinaldo azevedo desmascarado policia federal ...
3  fake  relatorio assustador bndes mostra dinheiro pub...
4  fake  radialista americano fala sobre pt vendem ilus...

In [19]:
news['class'] = news['label'] == 'true'

In [20]:
news.head()

  label                                  preprocessed_news  class
0  fake  katia abreu diz vai colocar expulsao moldura n...  False
1  fake  ray peita bolsonaro conservador fake entrevist...  False
2  fake  reinaldo azevedo desmascarado policia federal ...  False
3  fake  relatorio assustador bndes mostra dinheiro pub...  False
4  fake  radialista americano fala sobre pt vendem ilus...  False

# **Treinamento do modelo**

In [21]:
x = news['preprocessed_news']
y = news['class']

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

## Vetorização com TfidfVectorizer

In [26]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [74]:
vectorization_path = r'vectorizer\vectorizer.pkl'
with open(vectorization_path, 'wb') as f:
    pickle.dump(vectorization, f)

## Logistic Regression

In [34]:
LR = LogisticRegression()
LR.fit(xv_train, y_train)
LR.fit(xv_train, y_train)
pred_lr = LR.predict(xv_test)
LR.score(xv_test, y_test)
print (classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

       False       0.94      0.97      0.95       907
        True       0.97      0.93      0.95       893

    accuracy                           0.95      1800
   macro avg       0.95      0.95      0.95      1800
weighted avg       0.95      0.95      0.95      1800

## Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)
pred_dt = DT.predict(xv_test)
DT.score(xv_test, y_test)
print (classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

       False       0.94      0.97      0.95       907
        True       0.97      0.93      0.95       893

    accuracy                           0.95      1800
   macro avg       0.95      0.95      0.95      1800
weighted avg       0.95      0.95      0.95      1800

## Gradient Boost Classifier

In [36]:
from sklearn.ensemble import GradientBoostingClassifier

GB = GradientBoostingClassifier(random_state = 0)
GB.fit(xv_train, y_train)
pred_gb = GB.predict(xv_test)
GB.score(xv_test, y_test)
print(classification_report(y_test, pred_gb))

              precision    recall  f1-score   support

       False       0.94      0.96      0.95       907
        True       0.96      0.94      0.95       893

    accuracy                           0.95      1800
   macro avg       0.95      0.95      0.95      1800
weighted avg       0.95      0.95      0.95      1800

## Random Forest Classifier

In [37]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(random_state = 0)
RF.fit(xv_train, y_train)
pred_rf = RF.predict(xv_test)
RF.score(xv_test, y_test)
print (classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

       False       0.93      0.98      0.95       907
        True       0.98      0.92      0.95       893

    accuracy                           0.95      1800
   macro avg       0.95      0.95      0.95      1800
weighted avg       0.95      0.95      0.95      1800

## salvar os modelos treinados

In [40]:
import pickle

logistic_regression_pkl = r'models\logistic_regression__TfidfVectorizer.pkl'
decision_tree_classifier = r'models\decision_tree_classifier__TfidfVectorizer.pkl'
gradient_boost_classifier = r'models\gradient_boost_classifier__TfidfVectorizer.pkl'
random_forest_classifier_pkl = r'models\random_forest_classifier__TfidfVectorizer.pkl'

pickle.dump(LR, open(logistic_regression_pkl,'wb'))
pickle.dump(DT, open(decision_tree_classifier,'wb'))
pickle.dump(GB, open(gradient_boost_classifier,'wb'))
pickle.dump(RF, open(random_forest_classifier_pkl,'wb'))

##  Teste dos modelos

In [68]:
def predict_text(text):
    model = pickle.load(open(random_forest_classifier_pkl, 'rb'))
    text = text.lower()
    text = re.sub(r'\[.*?\]','',text)
    text = re.sub(r"\\W"," ",text)
    text = re.sub(r'https?://\S+|www\.\S+','',text)
    text = re.sub(r'<.*?>+',b'',text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation),'',text)
    text = re.sub(r'\w*\d\w*','',text)

    vector = vectorization.transform([text])
    
    return model.predict(vector)

In [70]:
print(predict_text(text))

[False]